[package]
name = "foldrs"
version = "0.1.0"
edition = "2024"
license = "MIT"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.53"
crossterm = "0.29.0"

[profile.dev]
debug = true
split-debuginfo = 'packed'
